output "cluster_endpoint" {
  description = "Endpoint for EKS control plane"
  value       = aws_eks_cluster.flow_cluster.endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane"
  value       = aws_eks_cluster.flow_cluster.vpc_config[0].cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module"
  value = {
    cluster_name = aws_eks_cluster.flow_cluster.name
    region       = var.aws_region
  }
}

output "load_balancer_hostname" {
  description = "Hostname of the load balancer"
  value       = kubernetes_ingress_v1.flow_ingress.status[0].load_balancer[0].ingress[0].hostname
}

output "cluster_name" {
  description = "Name of the EKS cluster"
  value       = aws_eks_cluster.flow_cluster.name
}