apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flow.fullname" . }}-config
  namespace: {{ .Values.namespace | default "flow" }}
data:
  N8N_HOST: {{ .Values.env.N8N_HOST | quote }}
  N8N_PORT: {{ .Values.env.N8N_PORT | quote }}
  N8N_PROTOCOL: {{ .Values.env.N8N_PROTOCOL | quote }}
  WEBHOOK_URL: {{ .Values.env.WEBHOOK_URL | quote }}
  WEBHOOK_TUNNEL_URL: {{ .Values.env.WEBHOOK_URL | quote }}
  N8N_METRICS: {{ .Values.env.N8N_METRICS | quote }}
  NODE_OPTIONS: "--max_old_space_size=8000"
  DB_TYPE: {{ .Values.env.DB_TYPE | quote }}
  DB_POSTGRESDB_HOST: {{ .Values.env.DB_POSTGRESDB_HOST | quote }}
  DB_POSTGRESDB_PORT: {{ .Values.env.DB_POSTGRESDB_PORT | quote }}
  DB_POSTGRESDB_DATABASE: {{ .Values.env.DB_POSTGRESDB_DATABASE | quote }}
  DB_POSTGRESDB_USER: {{ .Values.env.DB_POSTGRESDB_USER | quote }}
  DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"
  DB_POSTGRESDB_SSL_MODE: "require"
  {{- if .Values.env.QUEUE_BULL_REDIS_HOST }}
  QUEUE_BULL_REDIS_HOST: {{ .Values.env.QUEUE_BULL_REDIS_HOST | quote }}
  QUEUE_BULL_REDIS_PORT: {{ .Values.env.QUEUE_BULL_REDIS_PORT | quote }}
  {{- end }}