apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flow.fullname" . }}-secrets
  namespace: {{ .Values.namespace | default "flow" }}
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: {{ .Values.secrets.N8N_ENCRYPTION_KEY | quote }}
  OPENSEARCH_HOST: {{ .Values.secrets.OPENSEARCH_HOST | quote }}
  DB_POSTGRESDB_PASSWORD: {{ .Values.secrets.DB_POSTGRESDB_PASSWORD | quote }}