apiVersion: v1
kind: Secret
metadata:
  name: flow-secrets
  namespace: flow
type: Opaque
stringData:
  N8N_ENCRYPTION_KEY: "NmwxbwHRTVHUhxC4u8YQ0r6UUKzG4VOx"
  OPENSEARCH_HOST: "https://torqdata:CbEA1twubPUYAaaGde2C!@search-torqdata-datasets-ygg4qepiu7rkr4ry4hxhxzbqjy.aos.us-east-1.on.aws"
  DB_POSTGRESDB_PASSWORD: "C]e5H.bz|NGyd<IJMMaEaArI1V$j"